version: "3.8"

services:
  api:
    build: .
    ports:
      - "3010:8000"
    volumes:
      - .:/app_code
      - ./data:/app_code/data
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
